"""Change QuizLog and Category models to BasicAuditMixin

Revision ID: 6e8440925514
Revises: 5f54790875d7
Create Date: 2025-12-31 05:07:05.563074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8440925514'
down_revision: Union[str, None] = '5f54790875d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_categories', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'))
    op.add_column('quiz_categories', sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'))
    op.add_column('quiz_categories', sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'))
    op.add_column('quiz_categories', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'))
    op.add_column('quiz_categories', sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'))
    op.add_column('quiz_categories', sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'))
    op.create_index(op.f('ix_quiz_categories_created_by'), 'quiz_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_categories_deleted_by'), 'quiz_categories', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_quiz_categories_is_deleted'), 'quiz_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quiz_categories_updated_by'), 'quiz_categories', ['updated_by'], unique=False)
    op.add_column('quiz_logs', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'))
    op.add_column('quiz_logs', sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'))
    op.add_column('quiz_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'))
    op.add_column('quiz_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'))
    op.add_column('quiz_logs', sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'))
    op.add_column('quiz_logs', sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'))
    op.create_index(op.f('ix_quiz_logs_created_by'), 'quiz_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_logs_deleted_by'), 'quiz_logs', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_quiz_logs_is_deleted'), 'quiz_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quiz_logs_updated_by'), 'quiz_logs', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_logs_updated_by'), table_name='quiz_logs')
    op.drop_index(op.f('ix_quiz_logs_is_deleted'), table_name='quiz_logs')
    op.drop_index(op.f('ix_quiz_logs_deleted_by'), table_name='quiz_logs')
    op.drop_index(op.f('ix_quiz_logs_created_by'), table_name='quiz_logs')
    op.drop_column('quiz_logs', 'remark')
    op.drop_column('quiz_logs', 'deleted_by')
    op.drop_column('quiz_logs', 'deleted_at')
    op.drop_column('quiz_logs', 'is_deleted')
    op.drop_column('quiz_logs', 'updated_by')
    op.drop_column('quiz_logs', 'created_by')
    op.drop_index(op.f('ix_quiz_categories_updated_by'), table_name='quiz_categories')
    op.drop_index(op.f('ix_quiz_categories_is_deleted'), table_name='quiz_categories')
    op.drop_index(op.f('ix_quiz_categories_deleted_by'), table_name='quiz_categories')
    op.drop_index(op.f('ix_quiz_categories_created_by'), table_name='quiz_categories')
    op.drop_column('quiz_categories', 'remark')
    op.drop_column('quiz_categories', 'deleted_by')
    op.drop_column('quiz_categories', 'deleted_at')
    op.drop_column('quiz_categories', 'is_deleted')
    op.drop_column('quiz_categories', 'updated_by')
    op.drop_column('quiz_categories', 'created_by')
    # ### end Alembic commands ###
