"""Add telegram_avatar_file_id to user_extend

Revision ID: 07e1b7890fc8
Revises: c38a1ad9c80f
Create Date: 2025-12-29 05:31:33.931691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e1b7890fc8'
down_revision: Union[str, None] = 'c38a1ad9c80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_extend', sa.Column('telegram_avatar_file_id', sa.String(length=255), nullable=True, comment='用户最新上传的 Telegram 头像文件ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_extend', 'telegram_avatar_file_id')
    # ### end Alembic commands ###
