"""移除推荐相关字段_referrer_和_referrer_id

Revision ID: 53fad9070246
Revises: 32e642b09458
Create Date: 2025-10-22 23:38:41.736872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53fad9070246'
down_revision: Union[str, None] = '32e642b09458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_users_referrer_id'), table_name='users')
    op.drop_index(op.f('ix_users_referrer_id'), table_name='users')
    op.drop_column('users', 'referrer_id')
    op.drop_column('users', 'referrer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='推荐人信息，可选字段，存储推荐人的标识或描述信息'))
    op.add_column('users', sa.Column('referrer_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='推荐人的用户ID，可选字段，外键关联到users表的id字段'))
    op.create_index(op.f('ix_users_referrer_id'), 'users', ['referrer_id'], unique=False)
    op.create_index(op.f('idx_users_referrer_id'), 'users', ['referrer_id'], unique=False)
    # ### end Alembic commands ###
