"""添加剧集相关字段到NotificationModel和EmbyItemModel

Revision ID: b36134ce4a5f
Revises: 4a0148550cdb
Create Date: 2025-12-20 19:17:26.936162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b36134ce4a5f'
down_revision: Union[str, None] = '4a0148550cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emby_items_created_by'), table_name='emby_items')
    op.drop_index(op.f('ix_emby_items_deleted_by'), table_name='emby_items')
    op.drop_index(op.f('ix_emby_items_is_deleted'), table_name='emby_items')
    op.drop_index(op.f('ix_emby_items_updated_by'), table_name='emby_items')
    op.drop_table('emby_items')
    op.add_column('emby_notifications', sa.Column('item_type', sa.String(length=64), nullable=True, comment='媒体类型'))
    op.add_column('emby_notifications', sa.Column('series_id', sa.String(length=64), nullable=True, comment='剧集ID (SeriesId)'))
    op.add_column('emby_notifications', sa.Column('series_name', sa.String(length=255), nullable=True, comment='剧集名称'))
    op.add_column('emby_notifications', sa.Column('season_number', sa.Integer(), nullable=True, comment='季号 (ParentIndexNumber)'))
    op.add_column('emby_notifications', sa.Column('episode_number', sa.Integer(), nullable=True, comment='集号 (IndexNumber)'))
    op.create_index(op.f('ix_emby_notifications_series_id'), 'emby_notifications', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emby_notifications_series_id'), table_name='emby_notifications')
    op.drop_column('emby_notifications', 'episode_number')
    op.drop_column('emby_notifications', 'season_number')
    op.drop_column('emby_notifications', 'series_name')
    op.drop_column('emby_notifications', 'series_id')
    op.drop_column('emby_notifications', 'item_type')
    op.create_table('emby_items',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False, comment='Emby Item ID'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='媒体名称'),
    sa.Column('date_created', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True, comment='创建时间'),
    sa.Column('overview', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='简介'),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True, comment='类型'),
    sa.Column('people', mysql.JSON(), nullable=True, comment='人员信息'),
    sa.Column('tag_items', mysql.JSON(), nullable=True, comment='标签项'),
    sa.Column('image_tags', mysql.JSON(), nullable=True, comment='图片标签'),
    sa.Column('original_data', mysql.JSON(), nullable=True, comment='原始数据'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='备注（长文本）'),
    sa.Column('path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=True, comment='文件路径'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_emby_items_updated_by'), 'emby_items', ['updated_by'], unique=False)
    op.create_index(op.f('ix_emby_items_is_deleted'), 'emby_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emby_items_deleted_by'), 'emby_items', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_emby_items_created_by'), 'emby_items', ['created_by'], unique=False)
    # ### end Alembic commands ###
