"""Fix: 修复 emby_items 表缺少 BasicAuditMixin 字段

Revision ID: 9acdbef5c0fd
Revises: d59907a298a0
Create Date: 2025-12-15 07:16:22.462152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9acdbef5c0fd'
down_revision: Union[str, None] = 'd59907a298a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emby_items', sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'))
    op.add_column('emby_items', sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'))
    op.alter_column('emby_items', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='记录创建时间，自动设置为当前时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('emby_items', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='记录更新时间，创建时设置为当前时间，更新时自动更新',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('emby_items', 'created_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment='创建者用户ID，NULL表示系统创建',
               existing_nullable=True)
    op.alter_column('emby_items', 'updated_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment='最后更新者用户ID，NULL表示系统更新',
               existing_nullable=True)
    op.alter_column('emby_items', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='软删除标志，False表示未删除，True表示已删除',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('emby_items', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='软删除时间，NULL表示未删除，有值表示删除时间',
               existing_nullable=True)
    op.create_index(op.f('ix_emby_items_created_by'), 'emby_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_emby_items_deleted_by'), 'emby_items', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_emby_items_is_deleted'), 'emby_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emby_items_updated_by'), 'emby_items', ['updated_by'], unique=False)
    op.alter_column('emby_notifications', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='状态: pending_completion/pending_review/sent/failed',
               existing_comment='状态: pending/approved/sent/rejected/failed',
               existing_nullable=False)
    op.drop_index(op.f('ix_system_notifications_created_by'), table_name='emby_notifications')
    op.drop_index(op.f('ix_system_notifications_deleted_by'), table_name='emby_notifications')
    op.drop_index(op.f('ix_system_notifications_is_deleted'), table_name='emby_notifications')
    op.drop_index(op.f('ix_system_notifications_item_id'), table_name='emby_notifications')
    op.drop_index(op.f('ix_system_notifications_status'), table_name='emby_notifications')
    op.drop_index(op.f('ix_system_notifications_type'), table_name='emby_notifications')
    op.drop_index(op.f('ix_system_notifications_updated_by'), table_name='emby_notifications')
    op.create_index(op.f('ix_emby_notifications_created_by'), 'emby_notifications', ['created_by'], unique=False)
    op.create_index(op.f('ix_emby_notifications_deleted_by'), 'emby_notifications', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_emby_notifications_is_deleted'), 'emby_notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emby_notifications_item_id'), 'emby_notifications', ['item_id'], unique=False)
    op.create_index(op.f('ix_emby_notifications_status'), 'emby_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_emby_notifications_type'), 'emby_notifications', ['type'], unique=False)
    op.create_index(op.f('ix_emby_notifications_updated_by'), 'emby_notifications', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emby_notifications_updated_by'), table_name='emby_notifications')
    op.drop_index(op.f('ix_emby_notifications_type'), table_name='emby_notifications')
    op.drop_index(op.f('ix_emby_notifications_status'), table_name='emby_notifications')
    op.drop_index(op.f('ix_emby_notifications_item_id'), table_name='emby_notifications')
    op.drop_index(op.f('ix_emby_notifications_is_deleted'), table_name='emby_notifications')
    op.drop_index(op.f('ix_emby_notifications_deleted_by'), table_name='emby_notifications')
    op.drop_index(op.f('ix_emby_notifications_created_by'), table_name='emby_notifications')
    op.create_index(op.f('ix_system_notifications_updated_by'), 'emby_notifications', ['updated_by'], unique=False)
    op.create_index(op.f('ix_system_notifications_type'), 'emby_notifications', ['type'], unique=False)
    op.create_index(op.f('ix_system_notifications_status'), 'emby_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_system_notifications_item_id'), 'emby_notifications', ['item_id'], unique=False)
    op.create_index(op.f('ix_system_notifications_is_deleted'), 'emby_notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_notifications_deleted_by'), 'emby_notifications', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_system_notifications_created_by'), 'emby_notifications', ['created_by'], unique=False)
    op.alter_column('emby_notifications', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='状态: pending/approved/sent/rejected/failed',
               existing_comment='状态: pending_completion/pending_review/sent/failed',
               existing_nullable=False)
    op.drop_index(op.f('ix_emby_items_updated_by'), table_name='emby_items')
    op.drop_index(op.f('ix_emby_items_is_deleted'), table_name='emby_items')
    op.drop_index(op.f('ix_emby_items_deleted_by'), table_name='emby_items')
    op.drop_index(op.f('ix_emby_items_created_by'), table_name='emby_items')
    op.alter_column('emby_items', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='软删除时间，NULL表示未删除，有值表示删除时间',
               existing_nullable=True)
    op.alter_column('emby_items', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='软删除标志，False表示未删除，True表示已删除',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('emby_items', 'updated_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='最后更新者用户ID，NULL表示系统更新',
               existing_nullable=True)
    op.alter_column('emby_items', 'created_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='创建者用户ID，NULL表示系统创建',
               existing_nullable=True)
    op.alter_column('emby_items', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='记录更新时间，创建时设置为当前时间，更新时自动更新',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('emby_items', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='记录创建时间，自动设置为当前时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('emby_items', 'remark')
    op.drop_column('emby_items', 'deleted_by')
    # ### end Alembic commands ###
