"""Move avatar file_id to emby_users extra_data

Revision ID: 4df1548c123d
Revises: 07e1b7890fc8
Create Date: 2025-12-29 05:39:16.439066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4df1548c123d'
down_revision: Union[str, None] = '07e1b7890fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emby_user_history', sa.Column('extra_data', mysql.JSON(), nullable=True, comment='额外数据快照 (JSON)'))
    op.add_column('emby_users', sa.Column('extra_data', mysql.JSON(), nullable=True, comment='额外数据 (JSON)'))
    op.drop_column('user_extend', 'telegram_avatar_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_extend', sa.Column('telegram_avatar_file_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='用户最新上传的 Telegram 头像文件ID'))
    op.drop_column('emby_users', 'extra_data')
    op.drop_column('emby_user_history', 'extra_data')
    # ### end Alembic commands ###
