"""Fix: 移除currency_transactions.user_id的唯一约束

Revision ID: 05efdc073d3b
Revises: daf005fc71d6
Create Date: 2025-12-26 01:34:11.669817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05efdc073d3b'
down_revision: Union[str, None] = 'daf005fc71d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_transactions_user_id'), table_name='currency_transactions')
    op.create_index(op.f('ix_currency_transactions_user_id'), 'currency_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_transactions_user_id'), table_name='currency_transactions')
    op.create_index(op.f('ix_currency_transactions_user_id'), 'currency_transactions', ['user_id'], unique=True)
    # ### end Alembic commands ###
