"""add_category_to_quiz_tables

Revision ID: 5f54790875d7
Revises: 7fdc5a06355d
Create Date: 2025-12-31 02:07:21.954907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f54790875d7'
down_revision: Union[str, None] = '7fdc5a06355d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_images', sa.Column('category', sa.String(length=50), nullable=True, comment='分类'))
    op.add_column('quiz_questions', sa.Column('category', sa.String(length=50), nullable=True, comment='分类'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'category')
    op.drop_column('quiz_images', 'category')
    # ### end Alembic commands ###
