"""Add NotificationModel

Revision ID: d1394f131a24
Revises: b5d0d58ef028
Create Date: 2025-12-12 03:41:27.188205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1394f131a24'
down_revision: Union[str, None] = 'b5d0d58ef028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='大整型主键，适用于Telegram ID等大数值，不自增'),
    sa.Column('type', sa.String(length=64), nullable=False, comment='通知类型'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态: pending/approved/sent/rejected/failed'),
    sa.Column('item_id', sa.String(length=64), nullable=True, comment='Emby Item ID'),
    sa.Column('item_name', sa.String(length=255), nullable=True, comment='媒体名称'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='原始 Webhook 数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_system_notifications_created_by'), 'system_notifications', ['created_by'], unique=False)
    op.create_index(op.f('ix_system_notifications_deleted_by'), 'system_notifications', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_system_notifications_is_deleted'), 'system_notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_notifications_item_id'), 'system_notifications', ['item_id'], unique=False)
    op.create_index(op.f('ix_system_notifications_status'), 'system_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_system_notifications_type'), 'system_notifications', ['type'], unique=False)
    op.create_index(op.f('ix_system_notifications_updated_by'), 'system_notifications', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_notifications_updated_by'), table_name='system_notifications')
    op.drop_index(op.f('ix_system_notifications_type'), table_name='system_notifications')
    op.drop_index(op.f('ix_system_notifications_status'), table_name='system_notifications')
    op.drop_index(op.f('ix_system_notifications_item_id'), table_name='system_notifications')
    op.drop_index(op.f('ix_system_notifications_is_deleted'), table_name='system_notifications')
    op.drop_index(op.f('ix_system_notifications_deleted_by'), table_name='system_notifications')
    op.drop_index(op.f('ix_system_notifications_created_by'), table_name='system_notifications')
    op.drop_table('system_notifications')
    # ### end Alembic commands ###
