"""Add max_devices to EmbyUserModel

Revision ID: 81682f5d33de
Revises: 530f345f71dd
Create Date: 2025-12-22 21:14:16.906560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81682f5d33de'
down_revision: Union[str, None] = '530f345f71dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emby_users', sa.Column('max_devices', sa.Integer(), nullable=False, comment='最大允许设备数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emby_users', 'max_devices')
    # ### end Alembic commands ###
