"""添加消息实体字段_entities_和_caption_entities

Revision ID: e405e1effaed
Revises: 60caf28f7a25
Create Date: 2025-10-24 03:46:15.427859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e405e1effaed'
down_revision: Union[str, None] = '60caf28f7a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 entities 字段到 messages 表
    op.add_column('messages', sa.Column('entities', sa.Text(), nullable=True, comment='消息实体信息，JSON格式存储消息中的格式化信息（链接、提及、格式等）'))
    
    # 添加 caption_entities 字段到 messages 表
    op.add_column('messages', sa.Column('caption_entities', sa.Text(), nullable=True, comment='媒体说明实体信息，JSON格式存储媒体说明中的格式化信息'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除 caption_entities 字段
    op.drop_column('messages', 'caption_entities')
    
    # 移除 entities 字段
    op.drop_column('messages', 'entities')
    # ### end Alembic commands ###
