"""add_is_consumed_to_currency_transactions

Revision ID: 0354e5a53fea
Revises: 05efdc073d3b
Create Date: 2025-12-29 03:57:38.184225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0354e5a53fea'
down_revision: Union[str, None] = '05efdc073d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_transactions', sa.Column('is_consumed', sa.Boolean(), nullable=False, comment='是否已消耗(用于功能购买凭证)'))
    op.create_index(op.f('ix_currency_transactions_user_id'), 'currency_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_transactions_user_id'), table_name='currency_transactions')
    op.drop_column('currency_transactions', 'is_consumed')
    # ### end Alembic commands ###
