"""Add: 主图模型与用户偏好字段

Revision ID: a208cdb92c6c
Revises: 4df1548c123d
Create Date: 2025-12-29 18:16:58.890376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a208cdb92c6c'
down_revision: Union[str, None] = '4df1548c123d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_image_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('image_id', sa.Integer(), nullable=False, comment='关联 main_images.id'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间(含)'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间(含)'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级(小者先)'),
    sa.Column('only_sfw', sa.Boolean(), nullable=False, comment='仅用于 SFW 模式'),
    sa.Column('allow_nsfw', sa.Boolean(), nullable=False, comment='允许用于 NSFW 模式'),
    sa.Column('label', sa.String(length=64), nullable=True, comment='计划标签'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='扩展信息(JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_image_schedule_priority', 'main_image_schedule', ['priority'], unique=False)
    op.create_index('idx_image_schedule_window', 'main_image_schedule', ['start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_main_image_schedule_created_by'), 'main_image_schedule', ['created_by'], unique=False)
    op.create_index(op.f('ix_main_image_schedule_deleted_by'), 'main_image_schedule', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_main_image_schedule_is_deleted'), 'main_image_schedule', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_main_image_schedule_updated_by'), 'main_image_schedule', ['updated_by'], unique=False)
    op.create_table('main_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('file_id', sa.String(length=256), nullable=False, comment='Telegram 文件ID'),
    sa.Column('source_type', sa.String(length=16), nullable=False, comment='来源类型: photo/document'),
    sa.Column('mime_type', sa.String(length=64), nullable=True, comment='MIME 类型'),
    sa.Column('width', sa.Integer(), nullable=True, comment='宽像素'),
    sa.Column('height', sa.Integer(), nullable=True, comment='高像素'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('is_nsfw', sa.Boolean(), nullable=False, comment='是否 NSFW'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否参与投放'),
    sa.Column('caption', sa.Text(), nullable=True, comment='原始说明文本'),
    sa.Column('hash', sa.String(length=64), nullable=True, comment='文件哈希（去重）'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签数组'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='扩展信息(JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index('idx_main_images_enabled_nsfw', 'main_images', ['is_enabled', 'is_nsfw'], unique=False)
    op.create_index('idx_main_images_hash', 'main_images', ['hash'], unique=False)
    op.create_index(op.f('ix_main_images_created_by'), 'main_images', ['created_by'], unique=False)
    op.create_index(op.f('ix_main_images_deleted_by'), 'main_images', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_main_images_is_deleted'), 'main_images', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_main_images_updated_by'), 'main_images', ['updated_by'], unique=False)
    op.add_column('user_extend', sa.Column('display_mode', sa.String(length=16), nullable=False, comment='主图展示模式: sfw/nsfw/random'))
    op.add_column('user_extend', sa.Column('nsfw_unlocked', sa.Boolean(), nullable=False, comment='是否已解锁 NSFW 展示权限'))
    op.add_column('user_extend', sa.Column('last_image_id', sa.Integer(), nullable=True, comment='最近一次展示的主图ID'))
    op.add_column('user_extend', sa.Column('extra_data', sa.JSON(), nullable=True, comment='扩展信息(JSON)'))
    op.create_index('idx_user_extend_main_image_nsfw', 'user_extend', ['nsfw_unlocked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_extend_main_image_nsfw', table_name='user_extend')
    op.drop_column('user_extend', 'extra_data')
    op.drop_column('user_extend', 'last_image_id')
    op.drop_column('user_extend', 'nsfw_unlocked')
    op.drop_column('user_extend', 'display_mode')
    op.drop_index(op.f('ix_main_images_updated_by'), table_name='main_images')
    op.drop_index(op.f('ix_main_images_is_deleted'), table_name='main_images')
    op.drop_index(op.f('ix_main_images_deleted_by'), table_name='main_images')
    op.drop_index(op.f('ix_main_images_created_by'), table_name='main_images')
    op.drop_index('idx_main_images_hash', table_name='main_images')
    op.drop_index('idx_main_images_enabled_nsfw', table_name='main_images')
    op.drop_table('main_images')
    op.drop_index(op.f('ix_main_image_schedule_updated_by'), table_name='main_image_schedule')
    op.drop_index(op.f('ix_main_image_schedule_is_deleted'), table_name='main_image_schedule')
    op.drop_index(op.f('ix_main_image_schedule_deleted_by'), table_name='main_image_schedule')
    op.drop_index(op.f('ix_main_image_schedule_created_by'), table_name='main_image_schedule')
    op.drop_index('idx_image_schedule_window', table_name='main_image_schedule')
    op.drop_index('idx_image_schedule_priority', table_name='main_image_schedule')
    op.drop_table('main_image_schedule')
    # ### end Alembic commands ###
