"""Fix NotificationModel id auto-increment

Revision ID: b22cb84fc1d0
Revises: d1394f131a24
Create Date: 2025-12-12 05:04:52.018766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b22cb84fc1d0'
down_revision: Union[str, None] = 'd1394f131a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_notifications', 'id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               comment='自增整型主键',
               existing_comment='大整型主键，适用于Telegram ID等大数值，不自增',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('id'), table_name='system_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('id'), 'system_notifications', ['id'], unique=True)
    op.alter_column('system_notifications', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               comment='大整型主键，适用于Telegram ID等大数值，不自增',
               existing_comment='自增整型主键',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
