"""add_quiz_tables

Revision ID: 7fdc5a06355d
Revises: 3fcc347fdadc
Create Date: 2025-12-31 01:27:15.146155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7fdc5a06355d'
down_revision: Union[str, None] = '3fcc347fdadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_configs', 'save_bot_messages',
               existing_type=mysql.TINYINT(display_width=1),
               comment='保存机器人消息，默认True，是否保存机器人发送的消息',
               existing_comment='保存机器人消息，默认False，是否保存机器人发送的消息',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_configs', 'save_bot_messages',
               existing_type=mysql.TINYINT(display_width=1),
               comment='保存机器人消息，默认False，是否保存机器人发送的消息',
               existing_comment='保存机器人消息，默认True，是否保存机器人发送的消息',
               existing_nullable=False)
    # ### end Alembic commands ###
