"""添加操作者字段到所有模型

Revision ID: 32e642b09458
Revises: dbf5a57eee88
Create Date: 2025-10-22 16:24:09.703236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32e642b09458'
down_revision: Union[str, None] = 'dbf5a57eee88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作者ID，可选字段，执行操作的用户ID，关联到users表，系统操作时可为空'))
    op.alter_column('audit_logs', 'user_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='被操作用户ID，可选字段，关联到users表，记录操作的目标用户',
               existing_comment='执行操作的用户ID，可选字段，关联到users表，系统操作时可为空',
               existing_nullable=True)
    op.create_index('idx_audit_logs_operator_created', 'audit_logs', ['operator_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_operator_id'), 'audit_logs', ['operator_id'], unique=False)
    op.add_column('configs', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'))
    op.add_column('configs', sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'))
    op.add_column('configs', sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'))
    op.create_index(op.f('ix_configs_created_by'), 'configs', ['created_by'], unique=False)
    op.create_index(op.f('ix_configs_deleted_by'), 'configs', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_configs_updated_by'), 'configs', ['updated_by'], unique=False)
    op.drop_column('configs', 'operated_by')
    op.add_column('messages', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'))
    op.add_column('messages', sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'))
    op.add_column('messages', sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'))
    op.alter_column('messages', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='软删除标志，False表示未删除，True表示已删除',
               existing_comment='是否已删除，默认False，True表示此消息已被删除（软删除）',
               existing_nullable=False)
    op.alter_column('messages', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='软删除时间，NULL表示未删除，有值表示删除时间',
               existing_comment='删除时间，可选字段，消息被删除的时间',
               existing_nullable=True)
    op.drop_index(op.f('idx_messages_deleted'), table_name='messages')
    op.create_index(op.f('ix_messages_created_by'), 'messages', ['created_by'], unique=False)
    op.create_index(op.f('ix_messages_deleted_by'), 'messages', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_messages_updated_by'), 'messages', ['updated_by'], unique=False)
    op.add_column('statistics', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'))
    op.add_column('statistics', sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'))
    op.add_column('statistics', sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'))
    op.create_index(op.f('ix_statistics_created_by'), 'statistics', ['created_by'], unique=False)
    op.create_index(op.f('ix_statistics_deleted_by'), 'statistics', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_statistics_updated_by'), 'statistics', ['updated_by'], unique=False)
    op.drop_column('statistics', 'operated_by')
    op.add_column('user_states', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'))
    op.add_column('user_states', sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'))
    op.add_column('user_states', sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'))
    op.add_column('user_states', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'))
    op.add_column('user_states', sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'))
    op.create_index(op.f('ix_user_states_created_by'), 'user_states', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_states_deleted_by'), 'user_states', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_user_states_is_deleted'), 'user_states', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_states_updated_by'), 'user_states', ['updated_by'], unique=False)
    op.add_column('users', sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'))
    op.add_column('users', sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'))
    op.add_column('users', sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'))
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_index(op.f('ix_users_deleted_by'), 'users', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_users_updated_by'), 'users', ['updated_by'], unique=False)
    op.drop_column('users', 'operated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('operated_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='执行操作的用户ID，NULL表示系统操作'))
    op.drop_index(op.f('ix_users_updated_by'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_by'), table_name='users')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_index(op.f('ix_user_states_updated_by'), table_name='user_states')
    op.drop_index(op.f('ix_user_states_is_deleted'), table_name='user_states')
    op.drop_index(op.f('ix_user_states_deleted_by'), table_name='user_states')
    op.drop_index(op.f('ix_user_states_created_by'), table_name='user_states')
    op.drop_column('user_states', 'deleted_by')
    op.drop_column('user_states', 'deleted_at')
    op.drop_column('user_states', 'is_deleted')
    op.drop_column('user_states', 'updated_by')
    op.drop_column('user_states', 'created_by')
    op.add_column('statistics', sa.Column('operated_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='执行操作的用户ID，NULL表示系统操作'))
    op.drop_index(op.f('ix_statistics_updated_by'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_deleted_by'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_created_by'), table_name='statistics')
    op.drop_column('statistics', 'deleted_by')
    op.drop_column('statistics', 'updated_by')
    op.drop_column('statistics', 'created_by')
    op.drop_index(op.f('ix_messages_updated_by'), table_name='messages')
    op.drop_index(op.f('ix_messages_deleted_by'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_by'), table_name='messages')
    op.create_index(op.f('idx_messages_deleted'), 'messages', ['is_deleted', 'deleted_at'], unique=False)
    op.alter_column('messages', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='删除时间，可选字段，消息被删除的时间',
               existing_comment='软删除时间，NULL表示未删除，有值表示删除时间',
               existing_nullable=True)
    op.alter_column('messages', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否已删除，默认False，True表示此消息已被删除（软删除）',
               existing_comment='软删除标志，False表示未删除，True表示已删除',
               existing_nullable=False)
    op.drop_column('messages', 'deleted_by')
    op.drop_column('messages', 'updated_by')
    op.drop_column('messages', 'created_by')
    op.add_column('configs', sa.Column('operated_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='执行操作的用户ID，NULL表示系统操作'))
    op.drop_index(op.f('ix_configs_updated_by'), table_name='configs')
    op.drop_index(op.f('ix_configs_deleted_by'), table_name='configs')
    op.drop_index(op.f('ix_configs_created_by'), table_name='configs')
    op.drop_column('configs', 'deleted_by')
    op.drop_column('configs', 'updated_by')
    op.drop_column('configs', 'created_by')
    op.drop_index(op.f('ix_audit_logs_operator_id'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_operator_created', table_name='audit_logs')
    op.alter_column('audit_logs', 'user_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='执行操作的用户ID，可选字段，关联到users表，系统操作时可为空',
               existing_comment='被操作用户ID，可选字段，关联到users表，记录操作的目标用户',
               existing_nullable=True)
    op.drop_column('audit_logs', 'operator_id')
    # ### end Alembic commands ###
