"""Add source and extra_caption to QuizImageModel

Revision ID: 72db368f1634
Revises: 0735a4e5309a
Create Date: 2025-12-31 14:14:14.293235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72db368f1634'
down_revision: Union[str, None] = '0735a4e5309a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_quiz_categories_created_by'), 'quiz_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_categories_deleted_by'), 'quiz_categories', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_quiz_categories_is_deleted'), 'quiz_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quiz_categories_updated_by'), 'quiz_categories', ['updated_by'], unique=False)
    op.create_table('quiz_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='聊天ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('user_answer', sa.Integer(), nullable=True, comment='用户选择(NULL表示未答/超时)'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='是否正确'),
    sa.Column('reward_amount', sa.Integer(), nullable=False, comment='获得奖励'),
    sa.Column('time_taken', sa.Integer(), nullable=True, comment='耗时(ms)'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_logs_correct', 'quiz_logs', ['is_correct'], unique=False)
    op.create_index('idx_quiz_logs_question', 'quiz_logs', ['question_id'], unique=False)
    op.create_index('idx_quiz_logs_user', 'quiz_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_quiz_logs_created_by'), 'quiz_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_logs_deleted_by'), 'quiz_logs', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_quiz_logs_is_deleted'), 'quiz_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quiz_logs_updated_by'), 'quiz_logs', ['updated_by'], unique=False)
    op.create_table('quiz_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('file_id', sa.String(length=255), nullable=False, comment='Telegram File ID'),
    sa.Column('file_unique_id', sa.String(length=255), nullable=False, comment='Telegram File Unique ID'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='关联标签'),
    sa.Column('description', sa.Text(), nullable=True, comment='图片描述/备注'),
    sa.Column('image_source', sa.Text(), nullable=True, comment='图片来源(链接或文字)'),
    sa.Column('extra_caption', sa.Text(), nullable=True, comment='图片补充说明'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.ForeignKeyConstraint(['category_id'], ['quiz_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_images_active', 'quiz_images', ['is_active'], unique=False)
    op.create_index(op.f('ix_quiz_images_created_by'), 'quiz_images', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_images_deleted_by'), 'quiz_images', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_quiz_images_is_deleted'), 'quiz_images', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quiz_images_updated_by'), 'quiz_images', ['updated_by'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('question', sa.Text(), nullable=False, comment='题目描述'),
    sa.Column('options', sa.JSON(), nullable=False, comment='选项列表'),
    sa.Column('correct_index', sa.Integer(), nullable=False, comment='正确选项的索引'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='难度等级'),
    sa.Column('reward_base', sa.Integer(), nullable=False, comment='基础奖励(答错/低保)'),
    sa.Column('reward_bonus', sa.Integer(), nullable=False, comment='额外奖励(答对)'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.ForeignKeyConstraint(['category_id'], ['quiz_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_questions_active', 'quiz_questions', ['is_active'], unique=False)
    op.create_index('idx_quiz_questions_diff', 'quiz_questions', ['difficulty', 'is_active'], unique=False)
    op.create_index(op.f('ix_quiz_questions_created_by'), 'quiz_questions', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_questions_deleted_by'), 'quiz_questions', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_quiz_questions_is_deleted'), 'quiz_questions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quiz_questions_updated_by'), 'quiz_questions', ['updated_by'], unique=False)
    op.create_table('quiz_active_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID (单人单会话)'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='聊天ID'),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='题目消息ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('correct_index', sa.Integer(), nullable=False, comment='正确选项缓存'),
    sa.Column('expire_at', sa.Integer(), nullable=False, comment='过期时间戳'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_quiz_sessions_expire', 'quiz_active_sessions', ['expire_at'], unique=False)
    op.create_index('idx_quiz_sessions_user', 'quiz_active_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_active_sessions_created_by'), 'quiz_active_sessions', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_active_sessions_deleted_by'), 'quiz_active_sessions', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_quiz_active_sessions_is_deleted'), 'quiz_active_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quiz_active_sessions_updated_by'), 'quiz_active_sessions', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_active_sessions_updated_by'), table_name='quiz_active_sessions')
    op.drop_index(op.f('ix_quiz_active_sessions_is_deleted'), table_name='quiz_active_sessions')
    op.drop_index(op.f('ix_quiz_active_sessions_deleted_by'), table_name='quiz_active_sessions')
    op.drop_index(op.f('ix_quiz_active_sessions_created_by'), table_name='quiz_active_sessions')
    op.drop_index('idx_quiz_sessions_user', table_name='quiz_active_sessions')
    op.drop_index('idx_quiz_sessions_expire', table_name='quiz_active_sessions')
    op.drop_table('quiz_active_sessions')
    op.drop_index(op.f('ix_quiz_questions_updated_by'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_is_deleted'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_deleted_by'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_created_by'), table_name='quiz_questions')
    op.drop_index('idx_quiz_questions_diff', table_name='quiz_questions')
    op.drop_index('idx_quiz_questions_active', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_quiz_images_updated_by'), table_name='quiz_images')
    op.drop_index(op.f('ix_quiz_images_is_deleted'), table_name='quiz_images')
    op.drop_index(op.f('ix_quiz_images_deleted_by'), table_name='quiz_images')
    op.drop_index(op.f('ix_quiz_images_created_by'), table_name='quiz_images')
    op.drop_index('idx_quiz_images_active', table_name='quiz_images')
    op.drop_table('quiz_images')
    op.drop_index(op.f('ix_quiz_logs_updated_by'), table_name='quiz_logs')
    op.drop_index(op.f('ix_quiz_logs_is_deleted'), table_name='quiz_logs')
    op.drop_index(op.f('ix_quiz_logs_deleted_by'), table_name='quiz_logs')
    op.drop_index(op.f('ix_quiz_logs_created_by'), table_name='quiz_logs')
    op.drop_index('idx_quiz_logs_user', table_name='quiz_logs')
    op.drop_index('idx_quiz_logs_question', table_name='quiz_logs')
    op.drop_index('idx_quiz_logs_correct', table_name='quiz_logs')
    op.drop_table('quiz_logs')
    op.drop_index(op.f('ix_quiz_categories_updated_by'), table_name='quiz_categories')
    op.drop_index(op.f('ix_quiz_categories_is_deleted'), table_name='quiz_categories')
    op.drop_index(op.f('ix_quiz_categories_deleted_by'), table_name='quiz_categories')
    op.drop_index(op.f('ix_quiz_categories_created_by'), table_name='quiz_categories')
    op.drop_table('quiz_categories')
    # ### end Alembic commands ###
