"""Add: 为 EmbyItemModel 增加 path 字段

Revision ID: 4a0148550cdb
Revises: 9acdbef5c0fd
Create Date: 2025-12-15 22:50:40.590290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a0148550cdb'
down_revision: Union[str, None] = '9acdbef5c0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emby_items', sa.Column('path', sa.String(length=512), nullable=True, comment='文件路径'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emby_items', 'path')
    # ### end Alembic commands ###
