"""Add unique constraint to currency_product name

Revision ID: c38a1ad9c80f
Revises: 0354e5a53fea
Create Date: 2025-12-29 04:56:01.281932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38a1ad9c80f'
down_revision: Union[str, None] = '0354e5a53fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='商品名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品描述'),
    sa.Column('price', sa.Integer(), nullable=False, comment='价格(代币)'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='分类'),
    sa.Column('action_type', sa.String(length=32), nullable=False, comment='行为类型'),
    sa.Column('stock', sa.Integer(), server_default=sa.text('-1'), nullable=False, comment='库存'),
    sa.Column('visible_conditions', sa.JSON(), nullable=True, comment='可见条件'),
    sa.Column('purchase_conditions', sa.JSON(), nullable=True, comment='购买条件'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='上架时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='下架时间'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否上架'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_currency_products_cat_active', 'currency_products', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_currency_products_action_type'), 'currency_products', ['action_type'], unique=False)
    op.create_index(op.f('ix_currency_products_category'), 'currency_products', ['category'], unique=False)
    op.create_index(op.f('ix_currency_products_created_by'), 'currency_products', ['created_by'], unique=False)
    op.create_index(op.f('ix_currency_products_deleted_by'), 'currency_products', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_currency_products_is_deleted'), 'currency_products', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_currency_products_updated_by'), 'currency_products', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_products_updated_by'), table_name='currency_products')
    op.drop_index(op.f('ix_currency_products_is_deleted'), table_name='currency_products')
    op.drop_index(op.f('ix_currency_products_deleted_by'), table_name='currency_products')
    op.drop_index(op.f('ix_currency_products_created_by'), table_name='currency_products')
    op.drop_index(op.f('ix_currency_products_category'), table_name='currency_products')
    op.drop_index(op.f('ix_currency_products_action_type'), table_name='currency_products')
    op.drop_index('idx_currency_products_cat_active', table_name='currency_products')
    op.drop_table('currency_products')
    # ### end Alembic commands ###
