"""rename_media_file_label_to_description

Revision ID: 3fcc347fdadc
Revises: a208cdb92c6c
Create Date: 2025-12-30 20:41:33.652981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3fcc347fdadc'
down_revision: Union[str, None] = 'a208cdb92c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'label', new_column_name='description', existing_type=sa.String(length=255), existing_nullable=True, existing_comment='标签/备注', comment='说明/备注')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'description', new_column_name='label', existing_type=sa.String(length=255), existing_nullable=True, existing_comment='说明/备注', comment='标签/备注')
    # ### end Alembic commands ###
