"""Refactor QuizQuestion和QuizImage使用category_id外键

Revision ID: 0735a4e5309a
Revises: 6e8440925514
Create Date: 2025-12-31 05:41:24.039735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0735a4e5309a'
down_revision: Union[str, None] = '6e8440925514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_images', sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'))
    op.create_foreign_key(None, 'quiz_images', 'quiz_categories', ['category_id'], ['id'])
    op.drop_column('quiz_images', 'category')
    op.add_column('quiz_questions', sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'))
    op.create_foreign_key(None, 'quiz_questions', 'quiz_categories', ['category_id'], ['id'])
    op.drop_column('quiz_questions', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='分类'))
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.drop_column('quiz_questions', 'category_id')
    op.add_column('quiz_images', sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='分类'))
    op.drop_constraint(None, 'quiz_images', type_='foreignkey')
    op.drop_column('quiz_images', 'category_id')
    # ### end Alembic commands ###
