"""创建用户求片/投稿表

Revision ID: 60cd7c9b1515
Revises: 2026_01_03_创建媒体库分类表
Create Date: 2026-01-03 21:24:12.996351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60cd7c9b1515'
down_revision: Union[str, None] = '2026_01_03_创建媒体库分类表'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题，必填'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型：request=求片，submit=投稿'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID，必填'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending=待审核，approved=已通过，rejected=已拒绝'),
    sa.Column('reward_base', sa.Integer(), nullable=False, comment='基础奖励'),
    sa.Column('reward_bonus', sa.Integer(), nullable=False, comment='额外奖励'),
    sa.Column('image_file_id', sa.String(length=255), nullable=True, comment='Telegram图片File ID'),
    sa.Column('image_file_unique_id', sa.String(length=255), nullable=True, comment='Telegram图片File Unique ID'),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True, comment='审核者用户ID'),
    sa.Column('review_time', sa.String(length=50), nullable=True, comment='审核时间'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核评论'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=False, comment='投稿者用户ID'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_submissions_category', 'user_submissions', ['category_id'], unique=False)
    op.create_index('idx_user_submissions_created', 'user_submissions', ['created_at'], unique=False)
    op.create_index('idx_user_submissions_status', 'user_submissions', ['status'], unique=False)
    op.create_index('idx_user_submissions_submitter', 'user_submissions', ['submitter_id'], unique=False)
    op.create_index('idx_user_submissions_type', 'user_submissions', ['type'], unique=False)
    op.create_index(op.f('ix_user_submissions_created_by'), 'user_submissions', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_submissions_deleted_by'), 'user_submissions', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_user_submissions_is_deleted'), 'user_submissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_submissions_updated_by'), 'user_submissions', ['updated_by'], unique=False)
    # op.drop_index(op.f('idx_user_states_activity'), table_name='user_states')
    # op.drop_index(op.f('idx_user_states_complex'), table_name='user_states')
    # op.drop_index(op.f('idx_user_states_control'), table_name='user_states')
    # op.drop_index(op.f('idx_user_states_created'), table_name='user_states')
    # op.drop_index(op.f('idx_user_states_expires'), table_name='user_states')
    # op.drop_index(op.f('idx_user_states_priority'), table_name='user_states')
    # op.drop_index(op.f('idx_user_states_state'), table_name='user_states')
    # op.drop_index(op.f('idx_user_states_stats'), table_name='user_states')
    # op.drop_index(op.f('idx_user_states_updated'), table_name='user_states')
    # op.drop_index(op.f('ix_user_states_created_by'), table_name='user_states')
    # op.drop_index(op.f('ix_user_states_deleted_by'), table_name='user_states')
    # op.drop_index(op.f('ix_user_states_expires_at'), table_name='user_states')
    # op.drop_index(op.f('ix_user_states_is_active'), table_name='user_states')
    # op.drop_index(op.f('ix_user_states_is_deleted'), table_name='user_states')
    # op.drop_index(op.f('ix_user_states_last_activity_at'), table_name='user_states')
    # op.drop_index(op.f('ix_user_states_state'), table_name='user_states')
    # op.drop_index(op.f('ix_user_states_state_type'), table_name='user_states')
    # op.drop_index(op.f('ix_user_states_updated_by'), table_name='user_states')
    op.drop_table('user_states')
    op.alter_column('emby_media_categories', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='自增整型主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('emby_media_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='记录创建时间，自动设置为当前时间',
               existing_nullable=False)
    op.alter_column('emby_media_categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='记录更新时间，创建时设置为当前时间，更新时自动更新',
               existing_nullable=False)
    op.alter_column('emby_media_categories', 'created_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment='创建者用户ID，NULL表示系统创建',
               existing_nullable=True)
    op.alter_column('emby_media_categories', 'updated_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment='最后更新者用户ID，NULL表示系统更新',
               existing_nullable=True)
    op.alter_column('emby_media_categories', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='软删除标志，False表示未删除，True表示已删除',
               existing_nullable=False)
    op.alter_column('emby_media_categories', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='软删除时间，NULL表示未删除，有值表示删除时间',
               existing_nullable=True)
    op.alter_column('emby_media_categories', 'deleted_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment='删除者用户ID，NULL表示系统删除',
               existing_nullable=True)
    op.alter_column('emby_media_categories', 'remark',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='备注（长文本）',
               existing_nullable=True)
    op.drop_index(op.f('ix_emby_media_categories_is_enabled'), table_name='emby_media_categories')
    op.drop_index(op.f('ix_emby_media_categories_name'), table_name='emby_media_categories')
    op.drop_index(op.f('ix_emby_media_categories_sort_order'), table_name='emby_media_categories')
    op.create_index(op.f('ix_emby_media_categories_created_by'), 'emby_media_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_emby_media_categories_deleted_by'), 'emby_media_categories', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_emby_media_categories_is_deleted'), 'emby_media_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emby_media_categories_updated_by'), 'emby_media_categories', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emby_media_categories_updated_by'), table_name='emby_media_categories')
    op.drop_index(op.f('ix_emby_media_categories_is_deleted'), table_name='emby_media_categories')
    op.drop_index(op.f('ix_emby_media_categories_deleted_by'), table_name='emby_media_categories')
    op.drop_index(op.f('ix_emby_media_categories_created_by'), table_name='emby_media_categories')
    op.create_index(op.f('ix_emby_media_categories_sort_order'), 'emby_media_categories', ['sort_order'], unique=False)
    op.create_index(op.f('ix_emby_media_categories_name'), 'emby_media_categories', ['name'], unique=True)
    op.create_index(op.f('ix_emby_media_categories_is_enabled'), 'emby_media_categories', ['is_enabled'], unique=False)
    op.alter_column('emby_media_categories', 'remark',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='备注（长文本）',
               existing_nullable=True)
    op.alter_column('emby_media_categories', 'deleted_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='删除者用户ID，NULL表示系统删除',
               existing_nullable=True)
    op.alter_column('emby_media_categories', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='软删除时间，NULL表示未删除，有值表示删除时间',
               existing_nullable=True)
    op.alter_column('emby_media_categories', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='软删除标志，False表示未删除，True表示已删除',
               existing_nullable=False)
    op.alter_column('emby_media_categories', 'updated_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='最后更新者用户ID，NULL表示系统更新',
               existing_nullable=True)
    op.alter_column('emby_media_categories', 'created_by',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='创建者用户ID，NULL表示系统创建',
               existing_nullable=True)
    op.alter_column('emby_media_categories', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='记录更新时间，创建时设置为当前时间，更新时自动更新',
               existing_nullable=False)
    op.alter_column('emby_media_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='记录创建时间，自动设置为当前时间',
               existing_nullable=False)
    op.alter_column('emby_media_categories', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='自增整型主键',
               existing_nullable=False,
               autoincrement=True)
    op.create_table('user_states',
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='用户ID，复合主键的一部分，标识状态所属的用户'),
    sa.Column('chat_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='聊天ID，复合主键的一部分，标识状态所属的聊天会话'),
    sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='当前状态，可选字段，存储用户的当前FSM状态标识'),
    sa.Column('state_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='状态类型，可选字段，使用StateType枚举值标识状态的分类'),
    sa.Column('previous_state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='前一个状态，可选字段，用于状态回滚和历史追踪'),
    sa.Column('priority', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False, comment='状态优先级，必填字段，用于状态冲突时的处理，默认为普通优先级'),
    sa.Column('data', mysql.JSON(), nullable=True, comment='状态数据，可选字段，JSON格式存储状态相关的数据和参数'),
    sa.Column('context', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='状态上下文，可选字段，存储状态的详细上下文信息'),
    sa.Column('state_metadata', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='状态元数据，可选字段，JSON格式存储额外的状态元信息'),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True, comment='过期时间，可选字段，状态的过期时间，过期后状态将被自动清理'),
    sa.Column('last_activity_at', mysql.DATETIME(), nullable=True, comment='最后活动时间，可选字段，记录用户在此状态下的最后活动时间'),
    sa.Column('duration_seconds', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='持续时间，可选字段，状态持续的秒数，用于统计和分析'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否激活，必填字段，标识状态是否处于激活状态，默认为True'),
    sa.Column('is_persistent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否持久化，必填字段，标识状态是否需要持久保存，默认为False'),
    sa.Column('is_locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否锁定，必填字段，标识状态是否被锁定不可修改，默认为False'),
    sa.Column('step_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='步骤计数，必填字段，记录在当前状态下执行的步骤数量，默认为0'),
    sa.Column('retry_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='重试次数，必填字段，记录状态操作的重试次数，默认为0'),
    sa.Column('error_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='错误次数，必填字段，记录在当前状态下发生的错误次数，默认为0'),
    sa.Column('tags', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='标签，可选字段，逗号分隔的标签列表，用于状态的分类和搜索'),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='备注，可选字段，状态的备注信息，用于调试和说明'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_states_updated_by'), 'user_states', ['updated_by'], unique=False)
    op.create_index(op.f('ix_user_states_state_type'), 'user_states', ['state_type'], unique=False)
    op.create_index(op.f('ix_user_states_state'), 'user_states', ['state'], unique=False)
    op.create_index(op.f('ix_user_states_last_activity_at'), 'user_states', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_user_states_is_deleted'), 'user_states', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_states_is_active'), 'user_states', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_states_expires_at'), 'user_states', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_states_deleted_by'), 'user_states', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_user_states_created_by'), 'user_states', ['created_by'], unique=False)
    op.create_index(op.f('idx_user_states_updated'), 'user_states', ['updated_at'], unique=False)
    op.create_index(op.f('idx_user_states_stats'), 'user_states', ['step_count', 'retry_count', 'error_count'], unique=False)
    op.create_index(op.f('idx_user_states_state'), 'user_states', ['state', 'state_type'], unique=False)
    op.create_index(op.f('idx_user_states_priority'), 'user_states', ['priority', 'is_active'], unique=False)
    op.create_index(op.f('idx_user_states_expires'), 'user_states', ['expires_at', 'is_active'], unique=False)
    op.create_index(op.f('idx_user_states_created'), 'user_states', ['created_at'], unique=False)
    op.create_index(op.f('idx_user_states_control'), 'user_states', ['is_active', 'is_persistent', 'is_locked'], unique=False)
    op.create_index(op.f('idx_user_states_complex'), 'user_states', ['user_id', 'state', 'is_active', 'expires_at'], unique=False)
    op.create_index(op.f('idx_user_states_activity'), 'user_states', ['last_activity_at', 'is_active'], unique=False)
    op.drop_index(op.f('ix_user_submissions_updated_by'), table_name='user_submissions')
    op.drop_index(op.f('ix_user_submissions_is_deleted'), table_name='user_submissions')
    op.drop_index(op.f('ix_user_submissions_deleted_by'), table_name='user_submissions')
    op.drop_index(op.f('ix_user_submissions_created_by'), table_name='user_submissions')
    op.drop_index('idx_user_submissions_type', table_name='user_submissions')
    op.drop_index('idx_user_submissions_submitter', table_name='user_submissions')
    op.drop_index('idx_user_submissions_status', table_name='user_submissions')
    op.drop_index('idx_user_submissions_created', table_name='user_submissions')
    op.drop_index('idx_user_submissions_category', table_name='user_submissions')
    op.drop_table('user_submissions')
    # ### end Alembic commands ###
