"""initial_schema

Revision ID: 7e608d3a299c
Revises: 
Create Date: 2026-01-04 21:08:36.195235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e608d3a299c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emby_library_new_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='通知标题'),
    sa.Column('type', sa.String(length=64), nullable=False, comment='通知类型'),
    sa.Column('status', sa.String(length=32), nullable=True, comment='状态: pending_completion/pending_review/sent/failed'),
    sa.Column('item_id', sa.String(length=64), nullable=True, comment='Emby Item ID'),
    sa.Column('item_name', sa.String(length=255), nullable=True, comment='媒体名称'),
    sa.Column('item_type', sa.String(length=64), nullable=True, comment='媒体类型'),
    sa.Column('series_id', sa.String(length=64), nullable=True, comment='剧集ID (SeriesId)'),
    sa.Column('series_name', sa.String(length=255), nullable=True, comment='剧集名称'),
    sa.Column('season_number', sa.Integer(), nullable=True, comment='季号 (ParentIndexNumber)'),
    sa.Column('episode_number', sa.Integer(), nullable=True, comment='集号 (IndexNumber)'),
    sa.Column('target_channel_id', sa.String(length=64), nullable=True, comment='目标频道ID'),
    sa.Column('target_user_id', sa.String(length=64), nullable=True, comment='需要额外通知的用户ID'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='原始 Webhook 数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emby_library_new_notifications_created_by'), 'emby_library_new_notifications', ['created_by'], unique=False)
    op.create_index(op.f('ix_emby_library_new_notifications_deleted_by'), 'emby_library_new_notifications', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_emby_library_new_notifications_is_deleted'), 'emby_library_new_notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emby_library_new_notifications_item_id'), 'emby_library_new_notifications', ['item_id'], unique=False)
    op.create_index(op.f('ix_emby_library_new_notifications_series_id'), 'emby_library_new_notifications', ['series_id'], unique=False)
    op.create_index(op.f('ix_emby_library_new_notifications_status'), 'emby_library_new_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_emby_library_new_notifications_type'), 'emby_library_new_notifications', ['type'], unique=False)
    op.create_index(op.f('ix_emby_library_new_notifications_updated_by'), 'emby_library_new_notifications', ['updated_by'], unique=False)
    op.create_table('emby_media_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='分类名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='分类描述'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序顺序'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emby_media_categories_created_by'), 'emby_media_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_emby_media_categories_deleted_by'), 'emby_media_categories', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_emby_media_categories_is_deleted'), 'emby_media_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emby_media_categories_updated_by'), 'emby_media_categories', ['updated_by'], unique=False)
    op.create_table('user_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增整型主键'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题，必填'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型：request=求片，submit=投稿'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID，必填'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending=待审核，approved=已通过，rejected=已拒绝'),
    sa.Column('reward_base', sa.Integer(), nullable=False, comment='基础奖励'),
    sa.Column('reward_bonus', sa.Integer(), nullable=False, comment='额外奖励'),
    sa.Column('image_file_id', sa.String(length=255), nullable=True, comment='Telegram图片File ID'),
    sa.Column('image_file_unique_id', sa.String(length=255), nullable=True, comment='Telegram图片File Unique ID'),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True, comment='审核者用户ID'),
    sa.Column('review_time', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核评论'),
    sa.Column('submitter_id', sa.BigInteger(), nullable=False, comment='投稿者用户ID'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展数据'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间，自动设置为当前时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间，创建时设置为当前时间，更新时自动更新'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者用户ID，NULL表示系统创建'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者用户ID，NULL表示系统更新'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标志，False表示未删除，True表示已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间，NULL表示未删除，有值表示删除时间'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='删除者用户ID，NULL表示系统删除'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（长文本）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_submissions_category', 'user_submissions', ['category_id'], unique=False)
    op.create_index('idx_user_submissions_created', 'user_submissions', ['created_at'], unique=False)
    op.create_index('idx_user_submissions_status', 'user_submissions', ['status'], unique=False)
    op.create_index('idx_user_submissions_submitter', 'user_submissions', ['submitter_id'], unique=False)
    op.create_index('idx_user_submissions_type', 'user_submissions', ['type'], unique=False)
    op.create_index(op.f('ix_user_submissions_created_by'), 'user_submissions', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_submissions_deleted_by'), 'user_submissions', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_user_submissions_is_deleted'), 'user_submissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_submissions_updated_by'), 'user_submissions', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_submissions_updated_by'), table_name='user_submissions')
    op.drop_index(op.f('ix_user_submissions_is_deleted'), table_name='user_submissions')
    op.drop_index(op.f('ix_user_submissions_deleted_by'), table_name='user_submissions')
    op.drop_index(op.f('ix_user_submissions_created_by'), table_name='user_submissions')
    op.drop_index('idx_user_submissions_type', table_name='user_submissions')
    op.drop_index('idx_user_submissions_submitter', table_name='user_submissions')
    op.drop_index('idx_user_submissions_status', table_name='user_submissions')
    op.drop_index('idx_user_submissions_created', table_name='user_submissions')
    op.drop_index('idx_user_submissions_category', table_name='user_submissions')
    op.drop_table('user_submissions')
    op.drop_index(op.f('ix_emby_media_categories_updated_by'), table_name='emby_media_categories')
    op.drop_index(op.f('ix_emby_media_categories_is_deleted'), table_name='emby_media_categories')
    op.drop_index(op.f('ix_emby_media_categories_deleted_by'), table_name='emby_media_categories')
    op.drop_index(op.f('ix_emby_media_categories_created_by'), table_name='emby_media_categories')
    op.drop_table('emby_media_categories')
    op.drop_index(op.f('ix_emby_library_new_notifications_updated_by'), table_name='emby_library_new_notifications')
    op.drop_index(op.f('ix_emby_library_new_notifications_type'), table_name='emby_library_new_notifications')
    op.drop_index(op.f('ix_emby_library_new_notifications_status'), table_name='emby_library_new_notifications')
    op.drop_index(op.f('ix_emby_library_new_notifications_series_id'), table_name='emby_library_new_notifications')
    op.drop_index(op.f('ix_emby_library_new_notifications_item_id'), table_name='emby_library_new_notifications')
    op.drop_index(op.f('ix_emby_library_new_notifications_is_deleted'), table_name='emby_library_new_notifications')
    op.drop_index(op.f('ix_emby_library_new_notifications_deleted_by'), table_name='emby_library_new_notifications')
    op.drop_index(op.f('ix_emby_library_new_notifications_created_by'), table_name='emby_library_new_notifications')
    op.drop_table('emby_library_new_notifications')
    # ### end Alembic commands ###
