"""remove_unique_user_id_from_quiz_session

Revision ID: 0e132f535c54
Revises: 83ea159c2541
Create Date: 2026-01-01 00:52:01.183150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e132f535c54'
down_revision: Union[str, None] = '83ea159c2541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_id'), table_name='quiz_active_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('user_id'), 'quiz_active_sessions', ['user_id'], unique=True)
    # ### end Alembic commands ###
