"""Change_review_time_to_DateTime

Revision ID: 9785b2a595da
Revises: 19a4c6386d0d
Create Date: 2026-01-04 20:16:10.239700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9785b2a595da'
down_revision: Union[str, None] = '19a4c6386d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_submissions', 'review_time',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.DateTime(),
               existing_comment='审核时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_submissions', 'review_time',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_comment='审核时间',
               existing_nullable=True)
    # ### end Alembic commands ###
