"""Add main image preference fields to UserExtendModel

Revision ID: 99247fb93307
Revises: 
Create Date: 2026-01-02 22:55:22.715450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99247fb93307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_logs', 'time_taken',
               existing_type=mysql.INTEGER(display_width=11),
               comment='耗时(秒)',
               existing_comment='耗时(ms)',
               existing_nullable=True)
    op.alter_column('user_extend', 'display_mode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=True,
               existing_comment='主图展示模式: sfw/nsfw/random')
    op.alter_column('user_extend', 'nsfw_unlocked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='是否已解锁 NSFW 展示权限')
    op.alter_column('users', 'is_bot',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='是否为机器人，普通用户为0')
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True,
               existing_comment='用户名（必填）')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               existing_comment='用户名（必填）')
    op.alter_column('users', 'is_bot',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否为机器人，普通用户为0')
    op.alter_column('user_extend', 'nsfw_unlocked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否已解锁 NSFW 展示权限')
    op.alter_column('user_extend', 'display_mode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               nullable=False,
               existing_comment='主图展示模式: sfw/nsfw/random')
    op.alter_column('quiz_logs', 'time_taken',
               existing_type=mysql.INTEGER(display_width=11),
               comment='耗时(ms)',
               existing_comment='耗时(秒)',
               existing_nullable=True)
    # ### end Alembic commands ###
