from aiogram.types import InlineKeyboardButton

from bot.keyboards.inline.constants import *

# ===== 用户功能 =====
PROFILE_BUTTON = InlineKeyboardButton(text=PROFILE_LABEL, callback_data=PROFILE_CALLBACK_DATA)
ACCOUNT_CENTER_BUTTON = InlineKeyboardButton(text=ACCOUNT_CENTER_LABEL, callback_data=ACCOUNT_CENTER_CALLBACK_DATA)
START_REGISTER_BUTTON = InlineKeyboardButton(text=START_REGISTER_LABEL, callback_data=START_REGISTER_CALLBACK_DATA)
CANCEL_REGISTER_BUTTON = InlineKeyboardButton(text=CANCEL_REGISTER_LABEL, callback_data=CANCEL_REGISTER_CALLBACK_DATA)

USER_INFO_BUTTON = InlineKeyboardButton(text=USER_INFO_LABEL, callback_data=USER_INFO_CALLBACK_DATA)
USER_LINES_BUTTON = InlineKeyboardButton(text=USER_LINES_LABEL, callback_data=USER_LINES_CALLBACK_DATA)
USER_DEVICES_BUTTON = InlineKeyboardButton(text=USER_DEVICES_LABEL, callback_data=USER_DEVICES_CALLBACK_DATA)
USER_PASSWORD_BUTTON = InlineKeyboardButton(text=USER_PASSWORD_LABEL, callback_data=USER_PASSWORD_CALLBACK_DATA)
USER_AVATAR_BUTTON = InlineKeyboardButton(text=USER_AVATAR_LABEL, callback_data=USER_AVATAR_CALLBACK_DATA)
USER_TAGS_BUTTON = InlineKeyboardButton(text=USER_TAGS_LABEL, callback_data=USER_TAGS_CALLBACK_DATA)
TAGS_CUSTOM_BUTTON = InlineKeyboardButton(text=TAGS_CUSTOM_LABEL, callback_data=TAGS_CUSTOM_CALLBACK_DATA)
TAGS_CLEAR_BUTTON = InlineKeyboardButton(text=TAGS_CLEAR_LABEL, callback_data=TAGS_CLEAR_CALLBACK_DATA)
TAGS_CANCEL_EDIT_BUTTON = InlineKeyboardButton(text=TAGS_CANCEL_EDIT_LABEL, callback_data=TAGS_CANCEL_EDIT_CALLBACK_DATA)
DAILY_CHECKIN_BUTTON = InlineKeyboardButton(text=DAILY_CHECKIN_LABEL, callback_data=DAILY_CHECKIN_CALLBACK_DATA)
ESSENCE_STORE_BUTTON = InlineKeyboardButton(text=ESSENCE_STORE_LABEL, callback_data=ESSENCE_STORE_CALLBACK_DATA)
BACK_TO_ACCOUNT_BUTTON = InlineKeyboardButton(text=BACK_TO_ACCOUNT_LABEL, callback_data=BACK_TO_ACCOUNT_CALLBACK_DATA)
CANCEL_PASSWORD_CHANGE_BUTTON = InlineKeyboardButton(text=CANCEL_PASSWORD_CHANGE_LABEL, callback_data=CANCEL_PASSWORD_CHANGE_CALLBACK_DATA)
BACK_TO_STORE_BUTTON = InlineKeyboardButton(text=BACK_TO_STORE_LABEL, callback_data=ESSENCE_STORE_CALLBACK_DATA)

# ===== 管理员功能 =====
ADMIN_PANEL_BUTTON = InlineKeyboardButton(text=ADMIN_PANEL_LABEL, callback_data=ADMIN_PANEL_CALLBACK_DATA)

# 一言管理按钮
HITOKOTO_BUTTON = InlineKeyboardButton(text=HITOKOTO_LABEL, callback_data=HITOKOTO_CALLBACK_DATA)



# 文案管理按钮
BACK_TO_COPYWRITING_BUTTON = InlineKeyboardButton(text=BACK_TO_COPYWRITING_LABEL, callback_data=ADMIN_COPYWRITING_CALLBACK_DATA)

# 商店管理按钮
STORE_ADMIN_BUTTON = InlineKeyboardButton(text=STORE_ADMIN_LABEL, callback_data=STORE_ADMIN_CALLBACK_DATA)
STORE_ADMIN_ADD_PRODUCT_BUTTON = InlineKeyboardButton(text=STORE_ADMIN_ADD_PRODUCT_LABEL, callback_data=STORE_ADMIN_ADD_PRODUCT_CALLBACK_DATA)
STORE_ADMIN_HISTORY_BUTTON = InlineKeyboardButton(text=STORE_ADMIN_HISTORY_LABEL, callback_data=STORE_ADMIN_HISTORY_CALLBACK_DATA)



BACK_TO_STORE_ADMIN_BUTTON = InlineKeyboardButton(text=BACK_TO_STORE_LABEL, callback_data=STORE_ADMIN_CALLBACK_DATA)


# 精粹管理按钮
CURRENCY_ADMIN_BUTTON = InlineKeyboardButton(text=CURRENCY_ADMIN_LABEL, callback_data=CURRENCY_ADMIN_CALLBACK_DATA)

# 主图管理按钮
MAIN_IMAGE_BACK_BUTTON = InlineKeyboardButton(text=MAIN_IMAGE_BACK_LABEL, callback_data=MAIN_IMAGE_ADMIN_CALLBACK_DATA)
MAIN_IMAGE_CANCEL_BUTTON = InlineKeyboardButton(text=MAIN_IMAGE_CANCEL_LABEL, callback_data=MAIN_IMAGE_ADMIN_CALLBACK_DATA)

# 新片通知相关按钮
NOTIFY_COMPLETE_BUTTON = InlineKeyboardButton(text=NOTIFY_COMPLETE_LABEL, callback_data=NOTIFY_COMPLETE_CALLBACK_DATA)
NOTIFY_PREVIEW_BUTTON = InlineKeyboardButton(text=NOTIFY_PREVIEW_LABEL, callback_data=NOTIFY_PREVIEW_CALLBACK_DATA)
NOTIFY_SEND_BUTTON = InlineKeyboardButton(text=NOTIFY_SEND_LABEL, callback_data=NOTIFY_SEND_CALLBACK_DATA)
NOTIFY_CONFIRM_SEND_BUTTON = InlineKeyboardButton(text=NOTIFY_CONFIRM_SEND_LABEL, callback_data=NOTIFY_CONFIRM_SEND_CALLBACK_DATA)
NOTIFY_CONFIRM_SEND_CANCEL_BUTTON = InlineKeyboardButton(text=NOTIFY_CONFIRM_SEND_CANCEL_LABEL, callback_data=NOTIFY_CONFIRM_SEND_CANCEL_CALLBACK_DATA)
NOTIFY_CLOSE_PREVIEW_BUTTON = InlineKeyboardButton(text=NOTIFY_CLOSE_PREVIEW_LABEL, callback_data=NOTIFY_CLOSE_PREVIEW_CALLBACK_DATA)

BACK_TO_ADMIN_PANEL_BUTTON = InlineKeyboardButton(text=BACK_TO_ADMIN_PANEL_LABEL, callback_data=BACK_TO_ADMIN_PANEL_CALLBACK_DATA)

# ===== 所有者功能 =====
OWNER_PANEL_BUTTON = InlineKeyboardButton(text=OWNER_PANEL_LABEL, callback_data=OWNER_PANEL_CALLBACK_DATA)
OWNER_ADMINS_BUTTON = InlineKeyboardButton(text=OWNER_ADMINS_LABEL, callback_data=OWNER_ADMINS_CALLBACK_DATA)
ADMIN_LIST_BUTTON = InlineKeyboardButton(text=ADMIN_LIST_LABEL, callback_data=ADMIN_LIST_VIEW_CALLBACK_DATA)
USER_FEATURES_PANEL_BUTTON = InlineKeyboardButton(text=USER_FEATURES_PANEL_LABEL, callback_data=USER_FEATURES_PANEL_CALLBACK_DATA)
ADMIN_FEATURES_PANEL_BUTTON = InlineKeyboardButton(text=ADMIN_FEATURES_PANEL_LABEL, callback_data=ADMIN_FEATURES_PANEL_CALLBACK_DATA)


BACK_TO_OWNER_PANEL_BUTTON = InlineKeyboardButton(text=BACK_TO_OWNER_PANEL_LABEL, callback_data=BACK_TO_OWNER_PANEL_CALLBACK_DATA)


# ===== 通用导航 =====
BACK_TO_HOME_BUTTON = InlineKeyboardButton(text=BACK_TO_HOME_LABEL, callback_data=BACK_TO_HOME_CALLBACK_DATA)


# ===== 主面板按钮 =====
# 主面板：普通用户
MAIN_USER_BUTTONS = [
    [PROFILE_BUTTON],
    [ACCOUNT_CENTER_BUTTON],
    [ESSENCE_STORE_BUTTON],
    [DAILY_CHECKIN_BUTTON],
]

# 主面板：管理员
MAIN_ADMIN_BUTTONS = MAIN_USER_BUTTONS + [[ADMIN_PANEL_BUTTON]]

# 主面板：所有者
MAIN_OWNER_BUTTONS = MAIN_ADMIN_BUTTONS + [[OWNER_PANEL_BUTTON]]

# ===== 用户功能 =====
USER_PANEL_BUTTONS = [
    [USER_INFO_BUTTON],
    [USER_LINES_BUTTON],
    [USER_DEVICES_BUTTON],
    [USER_TAGS_BUTTON],
    [USER_AVATAR_BUTTON],
    [USER_PASSWORD_BUTTON],
    [BACK_TO_HOME_BUTTON],
]

# ===== 所有者功能 =====
OWNER_PANEL_BUTTONS = [
    [OWNER_ADMINS_BUTTON],
    [USER_FEATURES_PANEL_BUTTON],
    [ADMIN_FEATURES_PANEL_BUTTON],
    [BACK_TO_HOME_BUTTON],
]
